name: Rust CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: [self-hosted, linux, rust]
    timeout-minutes: 60
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Toolchain information
        run: rustc --version --verbose && cargo --version
      - name: Restore Cargo cache
        uses: Swatinem/rust-cache@49a0bdc70d2e1b713ca9e2869b211fcce03d3c1c # v2
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
      - name: Run tests
        run: cargo test --workspace --all-features --locked
